import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // 1. HEADER
    portalName: "E-SEVA PORTAL",
    tagline: "Digital Services Made Easy",
    govTag: "GOVERNMENT OF TAMIL NADU E-SEVA SERVICES",
    home: "Home",
    services: "Services",
    eServices: "Services",
    allServices: "All Services",
    aboutUs: "About Us",
    about: "About Us",
    contactUs: "Contact Us",
    contact: "Contact Us",
    trackAppNav: "Track Application",
    checkStatus: "Track Application",
    trackApp: "Track Application",
    more: "More",
    login: "Login",
    registerNav: "Register",
    profileNav: "Profile",
    dashboardNav: "Dashboard",
    myApplicationsNav: "My Applications",
    logoutNav: "Logout",
    
    // 2. COMMON BUTTONS
    applyNow: "Apply Now",
    viewDetails: "View Details",
    learnMore: "Learn More",
    getStarted: "Get Started",
    submitBtn: "Submit",
    continueBtn: "Continue",
    nextBtn: "Next",
    previousBtn: "Previous",
    backBtn: "Back",
    cancelBtn: "Cancel",
    saveBtn: "Save",
    editBtn: "Edit",
    deleteBtn: "Delete",
    searchBtn: "Search",
    filterBtn: "Filter",
    clearBtn: "Clear",
    closeBtn: "Close",
    confirmBtn: "Confirm",
    downloadBtn: "Download",
    uploadBtn: "Upload",
    viewBtn: "View",
    updateBtn: "Update",
    refreshBtn: "Refresh",
    retryBtn: "Retry",

    // 3. SERVICE CATEGORIES
    catAadhaar: "Aadhaar Services",
    catPan: "PAN Services",
    catVoter: "Voter ID Services",
    catCertificate: "Certificate Services",
    catLandPatta: "Land & Patta Services",
    catPassport: "Passport Services",
    catDriving: "Driving Licence Services",
    catVehicle: "Vehicle Services",
    catBusiness: "Business Services",
    catUtility: "Utility Services",
    catOther: "Other Digital Services",

    // 4. AADHAAR SERVICES
    aadhaarEnrollment: "New Aadhaar Enrollment",
    aadhaarNameUpdate: "Aadhaar Name Update",
    aadhaarAddressUpdate: "Aadhaar Address Update",
    aadhaarMobileUpdate: "Aadhaar Mobile Number Update",
    aadhaarEmailUpdate: "Aadhaar Email Update",
    aadhaarDobUpdate: "Aadhaar Date of Birth Update",
    aadhaarGenderUpdate: "Aadhaar Gender Update",
    aadhaarPhotoUpdate: "Aadhaar Photo Update",
    aadhaarBiometricUpdate: "Aadhaar Biometric Update",
    aadhaarDocumentUpdate: "Aadhaar Document Update",
    aadhaarDownload: "Aadhaar Download",
    aadhaarPvc: "Aadhaar PVC Card",
    aadhaarStatusCheck: "Aadhaar Status Check",
    aadhaarCorrection: "Aadhaar Correction Assistance",
    aadhaarPanLink: "Aadhaar-PAN Linking Assistance",

    // 5. PAN SERVICES
    panNew: "New PAN Card",
    panCorrection: "PAN Card Correction",
    panReprint: "PAN Card Reprint",
    panStatusCheck: "PAN Status Check",
    panAadhaarLink: "PAN-Aadhaar Linking",
    panDownload: "PAN Download",

    // 6. COMMON FORM LABELS
    fullNameLabel: "Full Name",
    firstNameLabel: "First Name",
    lastNameLabel: "Last Name",
    dobLabel: "Date of Birth",
    genderLabel: "Gender",
    mobileLabel: "Mobile Number",
    emailLabel: "Email Address",
    fatherNameLabel: "Father's Name",
    motherNameLabel: "Mother's Name",
    addressLabel: "Address",
    doorNoLabel: "House / Door Number",
    streetLabel: "Street",
    areaLabel: "Area",
    cityTownLabel: "City / Town",
    districtLabel: "District",
    stateLabel: "State",
    pincodeLabel: "Pincode",

    // 7. DOCUMENTS
    documentsHeader: "Documents",
    uploadDocumentsHeader: "Upload Documents",
    requiredDocumentsHeader: "Required Documents",
    identityProof: "Identity Proof",
    addressProof: "Address Proof",
    dobProof: "Date of Birth Proof",
    documentNameLabel: "Document Name",
    chooseFileBtn: "Choose File",
    noFileSelected: "No File Selected",
    uploadSuccessful: "Upload Successful",
    uploadFailed: "Upload Failed",

    // 8. APPLICATION
    applicationLabel: "Application",
    applicationFormHeader: "Application Form",
    applicationDetailsHeader: "Application Details",
    applicationIdLabel: "Application ID",
    applicationStatusLabel: "Application Status",
    applicationDateLabel: "Application Date",
    submittedOnLabel: "Submitted On",
    reviewApplicationHeader: "Review Application",
    submitApplicationBtn: "Submit Application",
    trackApplicationHeader: "Track Application",

    // 9. APPLICATION STATUS
    statusDraft: "Draft",
    statusSubmitted: "Submitted",
    statusUnderReview: "Under Review",
    statusProcessing: "Processing",
    statusApproved: "Approved",
    statusCompleted: "Completed",
    statusRejected: "Rejected",

    // 10. PAYMENT
    paymentHeader: "Payment",
    paymentDetailsHeader: "Payment Details",
    serviceFeeLabel: "Service Fee",
    totalAmountLabel: "Total Amount",
    paymentStatusLabel: "Payment Status",
    payNowBtn: "Pay Now",
    paymentSuccessfulMsg: "Payment Successful",
    paymentFailedMsg: "Payment Failed",
    transactionIdLabel: "Transaction ID",
    paymentReceiptHeader: "Payment Receipt",

    payStatusPending: "Pending",
    payStatusProcessing: "Processing",
    payStatusPaid: "Paid",
    payStatusFailed: "Failed",
    payStatusCancelled: "Cancelled",
    payStatusRefunded: "Refunded",

    // 11. USER DASHBOARD
    dashDashboard: "Dashboard",
    dashMyApplications: "My Applications",
    dashRecentApplications: "Recent Applications",
    dashTotalApplications: "Total Applications",
    dashPendingApplications: "Pending Applications",
    dashCompletedApplications: "Completed Applications",
    dashProfileSettings: "Profile Settings",
    dashAccountSettings: "Account Settings",
    dashNotifications: "Notifications",

    // 12. LOGIN / REGISTER
    authWelcomeBack: "Welcome Back",
    authLoginSub: "Login to your account",
    authEmail: "Email",
    authPassword: "Password",
    authConfirmPassword: "Confirm Password",
    authForgotPass: "Forgot Password?",
    authDontHaveAccount: "Don't have an account?",
    authCreateAccount: "Create Account",
    authAlreadyHaveAccount: "Already have an account?",

    // 13. COMMON MESSAGES
    msgPleaseWait: "Please wait",
    msgLoading: "Loading...",
    msgNoDataFound: "No data found",
    msgNoAppsFound: "No applications found",
    msgSomethingWentWrong: "Something went wrong",
    msgPleaseTryAgain: "Please try again",
    msgAreYouSure: "Are you sure?",
    msgChangesSavedSuccess: "Changes saved successfully",
    msgAppSubmittedSuccess: "Application submitted successfully",

    // Hero & Extra Helpers
    heroTitle: "One Portal for All Digital Government Services",
    heroSubtitle: "Apply for Community, Income, Aadhaar, Patta, PAN, Voter ID and Utility services online with instant verification and SMS tracking.",
    searchPlaceholder: "Search services (Aadhaar, PAN, Patta, Income Certificate)...",
    activeServicesCount: "100+ Active Services",
    digitalProcessing: "100% Paperless & Secure",
    fastDelivery: "2-3 Days Fast Processing",
    allCategories: "All Service Categories",
    welcomeUser: "Welcome,",
    userDashboardTitle: "User Dashboard & Application Cockpit",
    userDashboardDesc: "Manage your applications, view progress, and access 100+ digital services.",
    quickActions: "Quick Actions",
    applyNewService: "Apply for New Service",
    trackAppStatus: "Track Application Status",
    viewPaymentLedger: "View Payment History",
    appId: "Application ID",
    serviceName: "Service Name",
    appliedDate: "Applied Date",
    status: "Status",
    action: "Action",
    trackTitle: "Track Application Status",
    trackSubtitle: "Enter your Application ID to view current progress and download issued certificates.",
    enterAppId: "Enter Application ID (e.g., APP-2026-8492)",
    trackNow: "Track Now",
    statusTimeline: "Application Processing Timeline",
    dateSubmitted: "Date Submitted",
    lastUpdated: "Last Updated",
    trackingHelp: "Need help tracking your application? Contact our 24/7 helpline at 1800-425-1337.",
    rememberMe: "Remember me",
    forgotPasswordLink: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    registerNow: "Register Now",
    loginBtn: "Sign In",
    registerBtn: "Create Account",
    resetPasswordBtn: "Send Reset Link",
    personalInfo: "Personal Information",
    saveChanges: "Save Changes",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    notificationPrefs: "Notification Preferences",
    emailNotifications: "Email Notifications",
    smsNotifications: "SMS Notifications",
    transactionId: "Transaction ID",
    paymentDate: "Payment Date",
    amountPaid: "Amount Paid",
    downloadReceiptBtn: "Download PDF Receipt",
    popularServices: "Popular E-Seva Digital Services",
    viewAllServices: "View All Directory →",
    howItWorks: "How E-Seva Portal Works",
    footerDesc: "Official Digital E-Seva Services Gateway empowering citizens with transparent, fast, and accessible digital governance.",
    quickLinks: "Quick Links",
    helpDesk: "Helpline & Support",
    tollFree: "Toll Free Helpline: 1800-425-1337",
    workingHours: "Mon - Sat: 9:00 AM - 6:00 PM",
    copyright: "© 2026 E-Seva Portal. Government of Tamil Nadu Digital Governance Project.",
    
    // STEP 5 HOMEPAGE & FOOTER TRANSLATIONS
    trustedPartner: "Your Trusted Digital Services Partner",
    heroDesc: "Access essential digital services quickly, easily and securely.",
    exploreServices: "Explore Services",
    trackAppHero: "Track Application",
    secureConvenient: "Secure & Convenient",
    easyAppProcess: "Easy Application Process",
    fastSupport: "Fast Support",
    ourServices: "Our Services",
    exploreDigitalServices: "Explore Our Digital Services",
    servicesCategories: "Services Categories",
    popularServicesTitle: "Popular Services",
    mostRequestedServices: "Most requested digital services",
    howItWorksTitle: "How It Works",
    stepChooseService: "Choose a Service",
    stepFillApp: "Fill Application",
    stepUploadDocs: "Upload Documents",
    stepMakePayment: "Make Payment",
    stepTrackApp: "Track Application",
    whyChooseUsTitle: "Why Choose Us?",
    easyProcess: "Easy Process",
    secureService: "Secure Service",
    transparentProcess: "Transparent Process",
    needHelpApp: "Need help with your application?",
    trackAnytime: "Track your application anytime.",
    simpleSecureConvenient: "Simple. Secure. Convenient.",
    needAssistance: "Need Assistance?",
    supportTeamHere: "Our support team is here to help you.",
    sendEnquiry: "Send Message",
    phoneSupport: "Phone Support",
    emailSupport: "Email Support",
    serviceLocation: "Service Location",
    supportHours: "Support Hours",
    sendUsMessage: "Send Us a Message",
    fillDetailsBelow: "Fill in the details below and our team will get in touch with you.",
    footerDisclaimer: "This is a private digital services assistance portal and is not an official government website.",
    connectWithUs: "Connect With Us",
    privacyPolicy: "Privacy Policy",
    termsConditions: "Terms & Conditions",
    refundPolicy: "Refund Policy",
    adminCockpit: "Admin Portal Cockpit",
    allRightsReserved: "All Rights Reserved.",
    searchServicesPlaceholder: "Search services...",
    loadingText: "Loading...",
    noServicesFound: "No services found",
    somethingWentWrong: "Something went wrong",
    tryAgainBtn: "Try Again",

    // STEP 6 ALL SERVICES & SERVICE DETAILS TRANSLATIONS
    allServices: "All Services",
    findServiceSubtitle: "Find the service you need",
    allCategoriesFilter: "All Categories",
    categoriesTitle: "Categories",
    filterTitle: "Filter",
    clearFiltersBtn: "Clear Filters",
    sortByTitle: "Sort By",
    sortPopular: "Popular",
    sortNewest: "Newest",
    sortPriceLowHigh: "Price: Low to High",
    sortPriceHighLow: "Price: High to Low",
    servicesCountSuffix: "Services",
    tryChangingSearch: "Try changing your search or filters.",
    serviceDetailsTitle: "Service Details",
    aboutThisService: "About this service",
    serviceFeeLabel: "Service Fee",
    processingTimeLabel: "Processing Time",
    requiredDocumentsTitle: "Required Documents",
    howItWorksTitle: "How It Works",
    eligibilityTitle: "Eligibility",
    importantInformationTitle: "Important Information",
    backToServicesBtn: "Back to Services",
    relatedServicesTitle: "Related Services",
    identityProofLabel: "Identity Proof",
    addressProofLabel: "Address Proof",
    dobProofLabel: "Date of Birth Proof",
    additionalDocsLabel: "Additional Documents",
    serviceNotFoundTitle: "Service not found",
    goBackBtn: "Go Back",

    // STEP 7 APPLICATION FORM, DOCUMENTS, REVIEW & SUCCESS TRANSLATIONS
    stepDetails: "Details",
    stepDocuments: "Documents",
    stepReview: "Review",
    stepPayment: "Payment",
    stepConfirmation: "Confirmation",
    applicantInformation: "Applicant Information",
    requiredFieldsNotice: "Required fields",
    requiredTag: "Required",
    optionalTag: "Optional",
    saveDraftBtn: "Save Draft",
    savingDraftText: "Saving...",
    continueToDocuments: "Continue to Documents",
    continueToReview: "Continue to Review",
    continueToPayment: "Continue to Payment",
    backToDetails: "Back to Details",
    backToDocuments: "Back to Documents",
    backToReview: "Back to Review",
    verifyNoticeTitle: "Notice:",
    verifyNoticeText: "Please verify your details carefully before continuing to document uploads.",
    uploadDocsStepTitle: "Step 02: Upload Required Proof Documents",
    chooseFileOrDrag: "Choose File or Drag & Drop",
    maxFileSizeText: "Max 5MB",
    uploadedSuccessfully: "Successfully Uploaded",
    replaceBtn: "Replace",
    removeBtn: "Remove",
    docNoticeTitle: "Document Notice:",
    docNoticeText: "Please upload clear and readable documents. Make sure the details match your application.",
    reviewStepTitle: "Step 03: Review Application Details",
    finalVerificationTag: "Final Verification",
    applicantDetailsTitle: "Applicant Details",
    customInputsTitle: "Custom Inputs",
    uploadedDocumentsTitle: "Uploaded Documents",
    feeBreakdownTitle: "Fee Breakdown",
    totalPayableLabel: "Total Payable",
    freeFacilitation: "FREE Facilitation",
    selectPaymentOption: "Select Payment Option",
    upiPaymentTitle: "UPI / QR Instant Payment",
    upiPaymentSub: "Google Pay, PhonePe, Paytm, BHIM & Any UPI App",
    cardPaymentTitle: "Credit / Debit Card",
    cardPaymentSub: "Visa, Mastercard, RuPay, Maestro Cards",
    netbankingTitle: "Net Banking",
    netbankingSub: "SBI, HDFC, ICICI, Axis & 50+ Indian Banks",
    walletTitle: "Digital Wallet",
    walletSub: "Paytm Wallet, Mobikwik & Amazon Pay",
    orderSummaryTitle: "Order Summary",
    finalAmountPayable: "Final Amount Payable",
    proceedToPay: "Proceed to Pay",
    submitFreeApp: "Submit Free Application",
    appSubmittedSuccessTitle: "Application Submitted Successfully",
    yourAppIdLabel: "YOUR APPLICATION ID",
    copyAppIdBtn: "Copy Application ID",
    copiedToClipboard: "Copied to Clipboard!",
    paymentConfirmationTitle: "Payment Confirmation",
    paidStatusTag: "PAID",
    paidAmountLabel: "Paid Amount",
    transactionRefLabel: "Transaction Ref",
    dateTimeLabel: "Date & Time",
    whatsNextTitle: "What's Next? Application Timeline",
    timelineStep1Title: "Application Received",
    timelineStep1Sub: "Logged into E-Seva portal system",
    timelineStep2Title: "Under Review",
    timelineStep2Sub: "Facilitation desk verifying proof uploads",
    timelineStep3Title: "Track & Receive",
    timelineStep3Sub: "Track status online for output certificate",
    downloadPrintReceipt: "Download / Print Receipt",
    maleGender: "Male",
    femaleGender: "Female",
    transgenderGender: "Transgender",

    // STEP 8 PAYMENT, SUCCESS, RECEIPT & TRACKER TRANSLATIONS
    paymentSummaryTitle: "Payment Summary",
    processingFeeLabel: "Processing Fee",
    securePaymentText: "Secure 256-bit Encrypted Payment",
    paymentProcessingTitle: "Payment Processing",
    pleaseWaitProcessing: "Please wait while we verify your transaction...",
    paymentSuccessfulTitle: "Payment Successful",
    copyIdBtn: "Copy ID",
    copiedLabel: "Copied!",
    viewReceiptBtn: "View Receipt",
    trackAppBtn: "Track Application",
    goToDashboardBtn: "Go to Dashboard",
    acknowledgementReceiptTitle: "Application Acknowledgement Receipt",
    digitalPortalTitle: "E-SEVA DIGITAL GOVERNANCE PORTAL",
    officialFilingSub: "Government Digital Services Application Center • e-Governance Division",
    officialReceiptAudit: "Official Filing Acknowledgement & Audit Voucher",
    currentStatusLabel: "Current Status",
    categoryAndServiceLabel: "Category & Service",
    applicantInfoSection: "1. Applicant Information",
    submittedServiceDetailsSection: "2. Submitted Service Details",
    feePaymentReceiptSection: "3. Fee & Payment Receipt Breakdown",
    facilitationNoticeDisclaimer: "Notice: Service charges displayed on this portal are facilitation and processing service charges. Official government statutory fees, where applicable, are handled separately.",
    digitallyAuthenticatedReceipt: "Digitally Authenticated E-Seva Receipt",
    keepAppIdSafeText: "Keep this Application ID safe for tracking status online",
    generatedOnText: "Generated",
    applicationStatusHeading: "APPLICATION STATUS",
    appRefIdLabel: "Application Reference ID",
    mobileOptionalLabel: "Mobile Number (Optional)",
    checkStatusBtn: "Check Application Status",
    appRecordNotFound: "Application Record Not Found",
    doubleCheckAppIdText: "Please double-check your Application Reference ID.",
    appLifecycleTimeline: "Application Lifecycle Timeline",
    currentStageBadge: "Current Stage",
    completedBadge: "Completed",
    auditHistoryLogTitle: "Audit History Log",
    submittedInformationTitle: "Submitted Information",
    uploadedProofDocsTitle: "Uploaded Proof Documents",
    viewFileBtn: "View File",
    exploreOtherServicesBtn: "Explore Other E-Services",
    needHelpWithApp: "Need help with your application?",
    contactSupportDeskBtn: "Contact Support Desk",
    applicationRejectedTitle: "Application Rejected",
    applicationRejectedDesc: "This application has been rejected by the verifying authority. Please check officer remarks for further details.",
    officerRemarksTitle: "Officer Remarks & Notes",
    noAuditEventsLogged: "No additional audit events logged.",
    noCustomFieldValues: "No custom field values recorded.",
    paymentInformationTitle: "Payment Information",
    totalFeeLabel: "Total Fee",
    txnIdLabel: "Txn",
    myPaymentLedgerTitle: "My Payment Transactions",
    paymentLedgerSubtitle: "Track online facilitation charges, download official receipts, and retry incomplete payment orders.",
    paymentAuditTrailTitle: "Payment Audit Trail",
    totalRecordsLabel: "Total Records",
    loadingLedgerText: "Loading transaction ledger...",
    noPaymentHistoryTitle: "No payment history recorded yet",
    noPaymentHistoryDesc: "Your service payment receipts will appear here once you submit an application.",
    browseServicesBtn: "Browse Services",
    receiptTxnHeader: "Receipt / Txn ID",
    appIdHeader: "Application ID",
    serviceHeader: "Service",
    amountHeader: "Amount",
    dateHeader: "Date",
    statusHeader: "Status",
    actionsHeader: "Actions",
    retryPaymentBtn: "Retry Payment",
    retrievingStatusRecord: "Retrieving Status Record...",

    // STEP 9 AUTH, DASHBOARD, PROFILE & NOTIFICATION KEYS
    welcomeBack: "Welcome Back",
    loginToAccount: "Login to your E-Seva Account",
    emailAddressLabel: "Email Address",
    mobileNumberLabel: "Mobile Number",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    rememberMeLabel: "Remember Me",
    forgotPasswordLink: "Forgot Password?",
    loginBtn: "Login",
    registerBtn: "Create Account",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    showPassword: "Show Password",
    hidePassword: "Hide Password",
    fullNameLabel: "Full Name",
    createAccountTitle: "Create an Account",
    forgotPasswordTitle: "Forgot Password?",
    forgotPasswordDesc: "Enter your registered email address to receive a password reset link.",
    sendResetLinkBtn: "Send Reset Link",
    backToLoginLink: "Back to Login",
    emailRequiredErr: "Email address is required",
    mobileRequiredErr: "Mobile number is required",
    passwordRequiredErr: "Password is required",
    invalidEmailOrPasswordErr: "Invalid email or password",
    invalidMobileErr: "Enter a valid mobile number",
    tryAgainText: "Please try again",
    nameRequiredErr: "Name is required",
    passwordsDoNotMatchErr: "Passwords do not match",
    passwordCriteriaErr: "Password must meet the required criteria",
    dashboardTitle: "Dashboard",
    welcomeUserPrefix: "Welcome,",
    totalApplicationsCard: "Total Applications",
    pendingCard: "Pending",
    underReviewCard: "Under Review",
    processingCard: "Processing",
    approvedCard: "Approved",
    completedCard: "Completed",
    rejectedCard: "Rejected",
    recentApplicationsTitle: "Recent Applications",
    viewAllBtn: "View All",
    quickActionsTitle: "Quick Actions",
    applyServiceAction: "Apply for a Service",
    trackAppAction: "Track Application",
    viewProfileAction: "View Profile",
    searchApplicationsPlaceholder: "Search applications...",
    filterLabel: "Filter",
    allFilter: "All",
    noApplicationsFound: "No Applications Found",
    noApplicationsDesc: "You have not submitted any applications yet.",
    profileTitle: "Profile",
    personalInfoTitle: "Personal Information",
    addressLabel: "Address",
    editProfileBtn: "Edit Profile",
    saveChangesBtn: "Save Changes",
    cancelBtn: "Cancel",
    accountSettingsTitle: "Account Settings",
    changePasswordTitle: "Change Password",
    notificationsTitle: "Notifications",
    languageTitle: "Language",
    securityTitle: "Security",
    markAsReadBtn: "Mark as Read",
    markAllAsReadBtn: "Mark All as Read",
    noNotificationsText: "No Notifications",
    confirmLogoutTitle: "Are you sure you want to logout?",
    yesLogoutBtn: "Yes, Logout"
  },
  ta: {
    // 1. HEADER
    portalName: "இ-சேவை போர்ட்டல்",
    tagline: "மின்னணு சேவைகள் எளிதாக",
    govTag: "தமிழ்நாடு அரசு மின்னணு இ-சேவை மையம்",
    home: "முகப்பு",
    services: "சேவைகள்",
    eServices: "சேவைகள்",
    allServices: "அனைத்து சேவைகள்",
    aboutUs: "எங்களைப் பற்றி",
    about: "எங்களைப் பற்றி",
    contactUs: "தொடர்புகொள்ள",
    contact: "தொடர்புகொள்ள",
    trackAppNav: "விண்ணப்பத்தை கண்காணிக்க",
    checkStatus: "விண்ணப்பத்தை கண்காணிக்க",
    trackApp: "விண்ணப்ப நிலை அறிய",
    more: "மேலும்",
    login: "உள்நுழைய",
    registerNav: "பதிவு செய்ய",
    profileNav: "சுயவிவரம்",
    dashboardNav: "முகப்புப்பலகை",
    myApplicationsNav: "எனது விண்ணப்பங்கள்",
    logoutNav: "வெளியேற",
    
    // 2. COMMON BUTTONS
    applyNow: "இப்போது விண்ணப்பிக்கவும்",
    viewDetails: "விவரங்களைப் பார்க்கவும்",
    learnMore: "மேலும் அறியவும்",
    getStarted: "தொடங்கவும்",
    submitBtn: "சமர்ப்பிக்கவும்",
    continueBtn: "தொடரவும்",
    nextBtn: "அடுத்து",
    previousBtn: "முந்தையது",
    backBtn: "பின்செல்",
    cancelBtn: "ரத்து செய்யவும்",
    saveBtn: "சேமிக்கவும்",
    editBtn: "திருத்தவும்",
    deleteBtn: "நீக்கவும்",
    searchBtn: "தேடவும்",
    filterBtn: "வடிகட்டி",
    clearBtn: "அழிக்கவும்",
    closeBtn: "மூடவும்",
    confirmBtn: "உறுதிப்படுத்தவும்",
    downloadBtn: "பதிவிறக்கவும்",
    uploadBtn: "பதிவேற்றவும்",
    viewBtn: "பார்க்கவும்",
    updateBtn: "புதுப்பிக்கவும்",
    refreshBtn: "புதுப்பிக்கவும்",
    retryBtn: "மீண்டும் முயற்சிக்கவும்",

    // 3. SERVICE CATEGORIES
    catAadhaar: "ஆதார் சேவைகள்",
    catPan: "PAN அட்டை சேவைகள்",
    catVoter: "வாக்காளர் அட்டை சேவைகள்",
    catCertificate: "சான்றிதழ் சேவைகள்",
    catLandPatta: "நிலம் மற்றும் பட்டா சேவைகள்",
    catPassport: "பாஸ்போர்ட் சேவைகள்",
    catDriving: "ஓட்டுநர் உரிமம் சேவைகள்",
    catVehicle: "வாகன சேவைகள்",
    catBusiness: "வணிக சேவைகள்",
    catUtility: "பயன்பாட்டு சேவைகள்",
    catOther: "பிற டிஜிட்டல் சேவைகள்",

    // 4. AADHAAR SERVICES
    aadhaarEnrollment: "புதிய ஆதார் பதிவு",
    aadhaarNameUpdate: "ஆதார் பெயர் புதுப்பிப்பு",
    aadhaarAddressUpdate: "ஆதார் முகவரி புதுப்பிப்பு",
    aadhaarMobileUpdate: "ஆதார் மொபைல் எண் புதுப்பிப்பு",
    aadhaarEmailUpdate: "ஆதார் மின்னஞ்சல் புதுப்பிப்பு",
    aadhaarDobUpdate: "ஆதார் பிறந்த தேதி புதுப்பிப்பு",
    aadhaarGenderUpdate: "ஆதார் பாலினம் புதுப்பிப்பு",
    aadhaarPhotoUpdate: "ஆதார் புகைப்பட புதுப்பிப்பு",
    aadhaarBiometricUpdate: "ஆதார் பயோமெட்ரிக் புதுப்பிப்பு",
    aadhaarDocumentUpdate: "ஆதார் ஆவண புதுப்பிப்பு",
    aadhaarDownload: "ஆதார் பதிவிறக்கம்",
    aadhaarPvc: "ஆதார் PVC அட்டை",
    aadhaarStatusCheck: "ஆதார் நிலையைச் சரிபார்க்கவும்",
    aadhaarCorrection: "ஆதார் திருத்த உதவி",
    aadhaarPanLink: "ஆதார்-PAN இணைப்பு உதவி",

    // 5. PAN SERVICES
    panNew: "புதிய PAN அட்டை",
    panCorrection: "PAN அட்டை திருத்தம்",
    panReprint: "PAN அட்டை மறுபதிப்பு",
    panStatusCheck: "PAN நிலையைச் சரிபார்க்கவும்",
    panAadhaarLink: "PAN-Aadhaar இணைப்பு",
    panDownload: "PAN பதிவிறக்கம்",

    // 6. COMMON FORM LABELS
    fullNameLabel: "முழுப் பெயர்",
    firstNameLabel: "முதல் பெயர்",
    lastNameLabel: "கடைசி பெயர்",
    dobLabel: "பிறந்த தேதி",
    genderLabel: "பாலினம்",
    mobileLabel: "மொபைல் எண்",
    emailLabel: "மின்னஞ்சல் முகவரி",
    fatherNameLabel: "தந்தையின் பெயர்",
    motherNameLabel: "தாயின் பெயர்",
    addressLabel: "முகவரி",
    doorNoLabel: "வீட்டு / கதவு எண்",
    streetLabel: "தெரு",
    areaLabel: "பகுதி",
    cityTownLabel: "நகரம் / ஊர்",
    districtLabel: "மாவட்டம்",
    stateLabel: "மாநிலம்",
    pincodeLabel: "அஞ்சல் குறியீடு",

    // 7. DOCUMENTS
    documentsHeader: "ஆவணங்கள்",
    uploadDocumentsHeader: "ஆவணங்களைப் பதிவேற்றவும்",
    requiredDocumentsHeader: "தேவையான ஆவணங்கள்",
    identityProof: "அடையாளச் சான்று",
    addressProof: "முகவரிச் சான்று",
    dobProof: "பிறந்த தேதி சான்று",
    documentNameLabel: "ஆவணத்தின் பெயர்",
    chooseFileBtn: "கோப்பைத் தேர்ந்தெடுக்கவும்",
    noFileSelected: "எந்தக் கோப்பும் தேர்ந்தெடுக்கப்படவில்லை",
    uploadSuccessful: "பதிவேற்றம் வெற்றிகரமாக முடிந்தது",
    uploadFailed: "பதிவேற்றம் தோல்வியடைந்தது",

    // 8. APPLICATION
    applicationLabel: "விண்ணப்பம்",
    applicationFormHeader: "விண்ணப்பப் படிவம்",
    applicationDetailsHeader: "விண்ணப்ப விவரங்கள்",
    applicationIdLabel: "விண்ணப்ப எண்",
    applicationStatusLabel: "விண்ணப்ப நிலை",
    applicationDateLabel: "விண்ணப்ப தேதி",
    submittedOnLabel: "சமர்ப்பிக்கப்பட்ட தேதி",
    reviewApplicationHeader: "விண்ணப்பத்தை மதிப்பாய்வு செய்யவும்",
    submitApplicationBtn: "விண்ணப்பத்தை சமர்ப்பிக்கவும்",
    trackApplicationHeader: "விண்ணப்பத்தை கண்காணிக்கவும்",

    // 9. APPLICATION STATUS
    statusDraft: "வரைவு",
    statusSubmitted: "சமர்ப்பிக்கப்பட்டது",
    statusUnderReview: "பரிசீலனையில் உள்ளது",
    statusProcessing: "செயலாக்கத்தில் உள்ளது",
    statusApproved: "அங்கீகரிக்கப்பட்டது",
    statusCompleted: "நிறைவு பெற்றது",
    statusRejected: "நிராகரிக்கப்பட்டது",

    // 10. PAYMENT
    paymentHeader: "கட்டணம்",
    paymentDetailsHeader: "கட்டண விவரங்கள்",
    serviceFeeLabel: "சேவை கட்டணம்",
    totalAmountLabel: "மொத்த தொகை",
    paymentStatusLabel: "கட்டண நிலை",
    payNowBtn: "இப்போது செலுத்தவும்",
    paymentSuccessfulMsg: "கட்டணம் வெற்றிகரமாக செலுத்தப்பட்டது",
    paymentFailedMsg: "கட்டணம் தோல்வியடைந்தது",
    transactionIdLabel: "பரிவர்த்தனை எண்",
    paymentReceiptHeader: "கட்டண ரசீது",

    payStatusPending: "நிலுவையில் உள்ளது",
    payStatusProcessing: "செயலாக்கத்தில் உள்ளது",
    payStatusPaid: "செலுத்தப்பட்டது",
    payStatusFailed: "தோல்வியடைந்தது",
    payStatusCancelled: "ரத்து செய்யப்பட்டது",
    payStatusRefunded: "பணம் திருப்பி வழங்கப்பட்டது",

    // 11. USER DASHBOARD
    dashDashboard: "முகப்புப்பலகை",
    dashMyApplications: "எனது விண்ணப்பங்கள்",
    dashRecentApplications: "சமீபத்திய விண்ணப்பங்கள்",
    dashTotalApplications: "மொத்த விண்ணப்பங்கள்",
    dashPendingApplications: "நிலுவையிலுள்ள விண்ணப்பங்கள்",
    dashCompletedApplications: "நிறைவு பெற்ற விண்ணப்பங்கள்",
    dashProfileSettings: "சுயவிவர அமைப்புகள்",
    dashAccountSettings: "கணக்கு அமைப்புகள்",
    dashNotifications: "அறிவிப்புகள்",

    // 12. LOGIN / REGISTER
    authWelcomeBack: "மீண்டும் வரவேற்கிறோம்",
    authLoginSub: "உங்கள் கணக்கில் உள்நுழையவும்",
    authEmail: "மின்னஞ்சல்",
    authPassword: "கடவுச்சொல்",
    authConfirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    authForgotPass: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    authDontHaveAccount: "கணக்கு இல்லையா?",
    authCreateAccount: "கணக்கை உருவாக்கவும்",
    authAlreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",

    // 13. COMMON MESSAGES
    msgPleaseWait: "தயவுசெய்து காத்திருக்கவும்",
    msgLoading: "ஏற்றப்படுகிறது...",
    msgNoDataFound: "தரவு எதுவும் கிடைக்கவில்லை",
    msgNoAppsFound: "விண்ணப்பங்கள் எதுவும் கிடைக்கவில்லை",
    msgSomethingWentWrong: "ஏதோ தவறு ஏற்பட்டுள்ளது",
    msgPleaseTryAgain: "தயவுசெய்து மீண்டும் முயற்சிக்கவும்",
    msgAreYouSure: "நீங்கள் உறுதியாக உள்ளீர்களா?",
    msgChangesSavedSuccess: "மாற்றங்கள் வெற்றிகரமாக சேமிக்கப்பட்டன",
    msgAppSubmittedSuccess: "விண்ணப்பம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது",

    // Hero & Extra Helpers
    heroTitle: "அனைத்து அரசு சேவைகளுக்கும் ஒரே இணையதளம்",
    heroSubtitle: "வருமானம், சாதி, ஆதார், பட்டா, பான், வாக்காளர் அட்டை மற்றும் பிற மின் சேவைகளுக்கு ஆன்லைனில் விண்ணப்பித்து உடனடி நிலை அறியலாம்.",
    searchPlaceholder: "சேவைகளைத் தேடவும் (ஆதார், பான், பட்டா, வருமானச் சான்றிதழ்)...",
    activeServicesCount: "100+ நேரலை சேவைகள்",
    digitalProcessing: "100% பாதுகாப்பான மின்னணு முறை",
    fastDelivery: "2-3 நாட்களில் விரைவு சேவை",
    allCategories: "அனைத்து சேவைப் பிரிவுகள்",
    welcomeUser: "வரவேற்கிறோம்,",
    userDashboardTitle: "பயனர் டாஷ்போர்டு & விண்ணப்ப மையம்",
    userDashboardDesc: "உங்கள் விண்ணப்பங்களைக் கண்காணிக்கலாம் மற்றும் 100+ சேவைகளுக்கு விண்ணப்பிக்கலாம்.",
    quickActions: "விரைவுச் செயல்பாடுகள்",
    applyNewService: "புதிய சேவைக்கு விண்ணப்பிக்க",
    trackAppStatus: "விண்ணப்ப நிலையை அறிய",
    viewPaymentLedger: "கட்டண வரலாற்றைப் பார்க்க",
    appId: "விண்ணப்ப எண்",
    serviceName: "சேவையின் பெயர்",
    appliedDate: "விண்ணப்பித்த தேதி",
    status: "தற்போதைய நிலை",
    action: "செயல்பாடு",
    trackTitle: "விண்ணப்ப நிலையை அறிதல்",
    trackSubtitle: "தற்போதைய நிலையைப் பார்க்க மற்றும் சான்றிதழ் பதிவிறக்கம் செய்ய விண்ணப்ப எண்ணை உள்ளிடவும்.",
    enterAppId: "விண்ணப்ப எண்ணை உள்ளிடவும் (எ.கா: APP-2026-8492)",
    trackNow: "நிலை அறிய",
    statusTimeline: "விண்ணப்ப பரிசீலனை நிலைகள்",
    dateSubmitted: "சமர்ப்பிக்கப்பட்ட தேதி",
    lastUpdated: "கடைசியாக புதுப்பிக்கப்பட்டது",
    trackingHelp: "உதவி தேவையா? கட்டணமில்லா உதவி எண்ணை அழைக்கவும்: 1800-425-1337.",
    rememberMe: "என்னை நினைவில் கொள்க",
    forgotPasswordLink: "கடவுச்சொல் மறந்துவிட்டதா?",
    dontHaveAccount: "கணக்கு இல்லையா?",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    registerNow: "இப்போதே பதிவு செய்ய",
    loginBtn: "உள்நுழைக",
    registerBtn: "கணக்கை உருவாக்கு",
    resetPasswordBtn: "மீட்டமைப்பு இணைப்பு அனுப்புக",
    personalInfo: "தனிப்பட்ட விவரங்கள்",
    saveChanges: "மாற்றங்களைச் சேமி",
    changePassword: "கடவுச்சொல்லை மாற்றுக",
    currentPassword: "தற்போதைய கடவுச்சொல்",
    newPassword: "புதிய கடவுச்சொல்",
    notificationPrefs: "அறிவிப்பு விருப்பங்கள்",
    emailNotifications: "மின்னஞ்சல் அறிவிப்புகள்",
    smsNotifications: "குறுஞ்செய்தி (SMS) அறிவிப்புகள்",
    transactionId: "பரிவர்த்தனை எண்",
    paymentDate: "செலுத்திய தேதி",
    amountPaid: "செலுத்தப்பட்ட தொகை",
    downloadReceiptBtn: "PDF ரசீது பதிவிறக்கம்",
    popularServices: "முக்கியமான இ-சேவைகள்",
    viewAllServices: "அனைத்து சேவைகளையும் பார்க்க →",
    howItWorks: "இ-சேவை போர்ட்டல் எவ்வாறு செயல்படுகிறது?",
    footerDesc: "பொதுமக்களுக்கு வேகமான, வெளிப்படையான டிஜிட்டல் அரசு சேவைகளை வழங்கும் அதிகாரப்பூர்வ இ-சேவை போர்ட்டல்.",
    quickLinks: "முக்கிய இணைப்புகள்",
    helpDesk: "உதவி மையம் & ஆதரவு",
    tollFree: "கட்டணமில்லா உதவி எண்: 1800-425-1337",
    workingHours: "திங்கள் - சனி: காலை 9:00 - மாலை 6:00",
    copyright: "© 2026 இ-சேவை போர்ட்டல். தமிழ்நாடு அரசு டிஜிட்டல் ஆளுகைத் திட்டம்.",

    // STEP 5 HOMEPAGE & FOOTER TRANSLATIONS
    trustedPartner: "உங்கள் நம்பகமான டிஜிட்டல் சேவைத் துணை",
    heroDesc: "தேவையான டிஜிட்டல் சேவைகளை விரைவாகவும் எளிதாகவும் பாதுகாப்பாகவும் பெறுங்கள்.",
    exploreServices: "சேவைகளைப் பார்க்கவும்",
    trackAppHero: "விண்ணப்பத்தை கண்காணிக்கவும்",
    secureConvenient: "பாதுகாப்பான மற்றும் வசதியான சேவை",
    easyAppProcess: "எளிய விண்ணப்ப செயல்முறை",
    fastSupport: "விரைவான உதவி",
    ourServices: "எங்கள் சேவைகள்",
    exploreDigitalServices: "எங்கள் டிஜிட்டல் சேவைகளைப் பாருங்கள்",
    servicesCategories: "சேவை வகைகள்",
    popularServicesTitle: "பிரபலமான சேவைகள்",
    mostRequestedServices: "அதிகம் பயன்படுத்தப்படும் டிஜிட்டல் சேவைகள்",
    howItWorksTitle: "எப்படி செயல்படுகிறது",
    stepChooseService: "ஒரு சேவையைத் தேர்ந்தெடுக்கவும்",
    stepFillApp: "விண்ணப்பத்தைப் பூர்த்தி செய்யவும்",
    stepUploadDocs: "ஆவணங்களைப் பதிவேற்றவும்",
    stepMakePayment: "கட்டணத்தைச் செலுத்தவும்",
    stepTrackApp: "விண்ணப்பத்தை கண்காணிக்கவும்",
    whyChooseUsTitle: "ஏன் எங்களைத் தேர்வு செய்ய வேண்டும்?",
    easyProcess: "எளிய செயல்முறை",
    secureService: "பாதுகாப்பான சேவை",
    transparentProcess: "வெளிப்படையான செயல்முறை",
    needHelpApp: "உங்கள் விண்ணப்பத்திற்கு உதவி தேவையா?",
    trackAnytime: "உங்கள் விண்ணப்பத்தின் நிலையை எப்போது வேண்டுமானாலும் கண்காணிக்கலாம்.",
    simpleSecureConvenient: "எளிமை. பாதுகாப்பு. வசதி.",
    needAssistance: "உதவி தேவையா?",
    supportTeamHere: "எங்கள் ஆதரவுக் குழு உங்களுக்கு உதவ தயாராக உள்ளது.",
    sendEnquiry: "விசாரணையை அனுப்பவும்",
    phoneSupport: "தொலைபேசி ஆதரவு",
    emailSupport: "மின்னஞ்சல் ஆதரவு",
    serviceLocation: "சேவை மையம்",
    supportHours: "ஆதரவு நேரம்",
    sendUsMessage: "செய்தி அனுப்பவும்",
    fillDetailsBelow: "கீழேயுள்ள விவரங்களைப் பூர்த்தி செய்து அனுப்பவும், எங்கள் குழு தொடர்பு கொள்ளும்.",
    footerDisclaimer: "இது ஒரு தனியார் டிஜிட்டல் சேவை உதவி தளமாகும். இது அரசு சார்ந்த அதிகாரப்பூர்வ இணையதளம் அல்ல.",
    connectWithUs: "எங்களுடன் இணையுங்கள்",
    privacyPolicy: "தனியுரிமைக் கொள்கை",
    termsConditions: "விதிமுறைகள் மற்றும் நிபந்தனைகள்",
    refundPolicy: "ரீஃபண்ட் கொள்கை",
    adminCockpit: "நிர்வாகி போர்ட்டல்",
    allRightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    searchServicesPlaceholder: "சேவைகளைத் தேடுங்கள்...",
    loadingText: "ஏற்றப்படுகிறது...",
    noServicesFound: "சேவைகள் எதுவும் கிடைக்கவில்லை",
    somethingWentWrong: "ஏதோ தவறு ஏற்பட்டுள்ளது",
    tryAgainBtn: "மீண்டும் முயற்சிக்கவும்",

    // STEP 6 ALL SERVICES & SERVICE DETAILS TRANSLATIONS
    allServices: "அனைத்து சேவைகள்",
    findServiceSubtitle: "உங்களுக்குத் தேவையான சேவையைத் தேடுங்கள்",
    allCategoriesFilter: "அனைத்து வகைகள்",
    categoriesTitle: "சேவை வகைகள்",
    filterTitle: "வடிகட்டி",
    clearFiltersBtn: "வடிகட்டிகளை அழிக்கவும்",
    sortByTitle: "வரிசைப்படுத்து",
    sortPopular: "பிரபலமானவை",
    sortNewest: "புதியவை",
    sortPriceLowHigh: "விலை: குறைவிலிருந்து அதிகம்",
    sortPriceHighLow: "விலை: அதிகத்திலிருந்து குறைவு",
    servicesCountSuffix: "சேவைகள்",
    tryChangingSearch: "உங்கள் தேடல் அல்லது வடிகட்டிகளை மாற்றிப் பார்க்கவும்.",
    serviceDetailsTitle: "சேவை விவரங்கள்",
    aboutThisService: "இந்த சேவையைப் பற்றி",
    serviceFeeLabel: "சேவை கட்டணம்",
    processingTimeLabel: "செயலாக்க நேரம்",
    requiredDocumentsTitle: "தேவையான ஆவணங்கள்",
    howItWorksTitle: "எப்படி செயல்படுகிறது",
    eligibilityTitle: "தகுதி",
    importantInformationTitle: "முக்கிய தகவல்",
    backToServicesBtn: "சேவைகளுக்குத் திரும்பவும்",
    relatedServicesTitle: "தொடர்புடைய சேவைகள்",
    identityProofLabel: "அடையாளச் சான்று",
    addressProofLabel: "முகவரிச் சான்று",
    dobProofLabel: "பிறந்த தேதி சான்று",
    additionalDocsLabel: "கூடுதல் ஆவணங்கள்",
    serviceNotFoundTitle: "சேவை கிடைக்கவில்லை",
    goBackBtn: "பின்செல்லவும்",

    // STEP 7 APPLICATION FORM, DOCUMENTS, REVIEW & SUCCESS TRANSLATIONS
    stepDetails: "விவரங்கள்",
    stepDocuments: "ஆவணங்கள்",
    stepReview: "சரிபார்ப்பு",
    stepPayment: "கட்டணம்",
    stepConfirmation: "உறுதிப்படுத்தல்",
    applicantInformation: "விண்ணப்பதாரர் தகவல்கள்",
    requiredFieldsNotice: "கட்டாய புலங்கள்",
    requiredTag: "கட்டாயம்",
    optionalTag: "விருப்பத்தேர்வு",
    saveDraftBtn: "வரைவாகச் சேமி",
    savingDraftText: "சேமிக்கப்படுகிறது...",
    continueToDocuments: "ஆவணங்களுக்குத் தொடரவும்",
    continueToReview: "மதிப்பாய்வுக்குத் தொடரவும்",
    continueToPayment: "கட்டணத்திற்குத் தொடரவும்",
    backToDetails: "விவரங்களுக்குத் திரும்பவும்",
    backToDocuments: "ஆவணங்களுக்குத் திரும்பவும்",
    backToReview: "மதிப்பாய்வுக்குத் திரும்பவும்",
    verifyNoticeTitle: "அறிவிப்பு:",
    verifyNoticeText: "ஆவணங்களைப் பதிவேற்றுவதற்கு முன் உங்கள் விவரங்களை கவனமாக சரிபார்க்கவும்.",
    uploadDocsStepTitle: "படி 02: தேவையான சான்று ஆவணங்களைப் பதிவேற்றவும்",
    chooseFileOrDrag: "கோப்பைத் தேர்ந்தெடுக்கவும் அல்லது இழுத்து இடவும்",
    maxFileSizeText: "அதிகபட்சம் 5MB",
    uploadedSuccessfully: "வெற்றிகரமாக பதிவேற்றப்பட்டது",
    replaceBtn: "மாற்றவும்",
    removeBtn: "அகற்றவும்",
    docNoticeTitle: "ஆவண அறிவிப்பு:",
    docNoticeText: "தெளிவான மற்றும் படிக்கக்கூடிய ஆவணங்களைப் பதிவேற்றவும். விவரங்கள் உங்கள் விண்ணப்பத்துடன் பொருந்துகிறதா என்பதை உறுதிப்படுத்தவும்.",
    reviewStepTitle: "படி 03: விண்ணப்ப விவரங்களை மதிப்பாய்வு செய்யவும்",
    finalVerificationTag: "இறுதி சரிபார்ப்பு",
    applicantDetailsTitle: "விண்ணப்பதாரர் விவரங்கள்",
    customInputsTitle: "சேவை சார்ந்த உள்ளீடுகள்",
    uploadedDocumentsTitle: "பதிவேற்றப்பட்ட ஆவணங்கள்",
    feeBreakdownTitle: "கட்டண விவரங்கள்",
    totalPayableLabel: "செலுத்த வேண்டிய மொத்தத் தொகை",
    freeFacilitation: "இலவச சேவை",
    selectPaymentOption: "கட்டண முறையைத் தேர்ந்தெடுக்கவும்",
    upiPaymentTitle: "UPI / QR உடனடி கட்டணம்",
    upiPaymentSub: "Google Pay, PhonePe, Paytm, BHIM மற்றும் பிற UPI செயலிகள்",
    cardPaymentTitle: "கிரெடிட் / டெபிட் கார்டு",
    cardPaymentSub: "Visa, Mastercard, RuPay, Maestro அட்டைகள்",
    netbankingTitle: "நெட் பேங்கிங்",
    netbankingSub: "SBI, HDFC, ICICI, Axis மற்றும் 50+ இந்திய வங்கிகள்",
    walletTitle: "டிஜிட்டல் வாலட்",
    walletSub: "Paytm Wallet, Mobikwik மற்றும் Amazon Pay",
    orderSummaryTitle: "ஆர்டர் சுருக்கம்",
    finalAmountPayable: "செலுத்த வேண்டிய இறுதித் தொகை",
    proceedToPay: "கட்டணம் செலுத்த தொடரவும்",
    submitFreeApp: "இலவச விண்ணப்பத்தை சமர்ப்பிக்கவும்",
    appSubmittedSuccessTitle: "விண்ணப்பம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது",
    yourAppIdLabel: "உங்கள் விண்ணப்ப எண்",
    copyAppIdBtn: "விண்ணப்ப எண்ணை நகலெடுக்கவும்",
    copiedToClipboard: "நகலெடுக்கப்பட்டது!",
    paymentConfirmationTitle: "கட்டண உறுதிப்படுத்தல்",
    paidStatusTag: "செலுத்தப்பட்டது",
    paidAmountLabel: "செலுத்தப்பட்ட தொகை",
    transactionRefLabel: "பரிவர்த்தனை எண்",
    dateTimeLabel: "தேதி மற்றும் நேரம்",
    whatsNextTitle: "அடுத்தது என்ன? விண்ணப்ப பரிசீலனை நிலைகள்",
    timelineStep1Title: "விண்ணப்பம் பெறப்பட்டது",
    timelineStep1Sub: "இ-சேவை போர்டல் அமைப்பில் பதிவு செய்யப்பட்டது",
    timelineStep2Title: "பரிசீலனையில் உள்ளது",
    timelineStep2Sub: "ஆவணங்கள் சரிபார்க்கப்பட்டு வருகின்றன",
    timelineStep3Title: "கண்காணித்து பெறவும்",
    timelineStep3Sub: "சான்றிதழ் பெற ஆன்லைனில் நிலை அறியலாம்",
    downloadPrintReceipt: "ரசீதை பதிவிறக்கம் / அச்சிடவும்",
    maleGender: "ஆண்",
    femaleGender: "பெண்",
    transgenderGender: "மூன்றாம் பாலினத்தவர்",

    // STEP 8 PAYMENT, SUCCESS, RECEIPT & TRACKER TRANSLATIONS
    paymentSummaryTitle: "கட்டண விவரம்",
    processingFeeLabel: "செயலாக்க கட்டணம்",
    securePaymentText: "பாதுகாப்பான 256-பிட் குறியாக்கப்பட்ட கட்டணம்",
    paymentProcessingTitle: "கட்டணம் செயலாக்கப்படுகிறது",
    pleaseWaitProcessing: "உங்கள் பரிவர்த்தனை சரிபார்க்கப்படும் வரை தயவுசெய்து காத்திருக்கவும்...",
    paymentSuccessfulTitle: "கட்டணம் வெற்றிகரமாக முடிந்தது",
    copyIdBtn: "எண்ணை நகலெடுக்கவும்",
    copiedLabel: "நகலெடுக்கப்பட்டது!",
    viewReceiptBtn: "ரசீதைப் பார்க்கவும்",
    trackAppBtn: "விண்ணப்ப நிலையைப் பார்க்கவும்",
    goToDashboardBtn: "டாஷ்போர்டுக்குச் செல்லவும்",
    acknowledgementReceiptTitle: "விண்ணப்ப ஒப்புதல் ரசீது",
    digitalPortalTitle: "இ-சேவை டிஜிட்டல் ஆளுமை போர்ட்டல்",
    officialFilingSub: "அரசு டிஜிட்டல் சேவைகள் விண்ணப்ப மையம் • மின்-ஆளுமைப் பிரிவு",
    officialReceiptAudit: "அதிகாரப்பூர்வ விண்ணப்ப ஒப்புதல் மற்றும் தணிக்கைச் சான்று",
    currentStatusLabel: "தற்போதைய நிலை",
    categoryAndServiceLabel: "பிரிவு & சேவை",
    applicantInfoSection: "1. விண்ணப்பதாரர் தகவல்கள்",
    submittedServiceDetailsSection: "2. சமர்ப்பிக்கப்பட்ட சேவை விவரங்கள்",
    feePaymentReceiptSection: "3. கட்டண விவரங்கள் மற்றும் கட்டண ரசீது",
    facilitationNoticeDisclaimer: "அறிவிப்பு: இந்த போர்ட்டலில் காட்டப்படும் சேவை கட்டணங்கள் ஒருங்கிணைப்பு மற்றும் செயலாக்க சேவை கட்டணங்கள் ஆகும். அதிகாரப்பூர்வ அரசு சட்டப்பூர்வ கட்டணங்கள் பொருந்தும் இடங்களில் தனியாக கையாளப்படும்.",
    digitallyAuthenticatedReceipt: "டிஜிட்டல் முறையில் அங்கீகரிக்கப்பட்ட இ-சேவை ரசீது",
    keepAppIdSafeText: "ஆன்லைனில் நிலை அறிய இந்த விண்ணப்ப எண்ணைப் பத்திரமாக வைத்திருக்கவும்",
    generatedOnText: "உருவாக்கப்பட்டது",
    applicationStatusHeading: "விண்ணப்ப நிலை",
    appRefIdLabel: "விண்ணப்ப எண்ணை உள்ளிடவும்",
    mobileOptionalLabel: "மொபைல் எண் (விருப்பத்தேர்வு)",
    checkStatusBtn: "நிலையைப் பார்க்கவும்",
    appRecordNotFound: "விண்ணப்பப் பதிவு எதுவும் கிடைக்கவில்லை",
    doubleCheckAppIdText: "தயவுசெய்து உங்கள் விண்ணப்ப எண்ணை சரிபார்க்கவும்.",
    appLifecycleTimeline: "விண்ணப்ப பரிசீலனை காலக்கோடு",
    currentStageBadge: "தற்போதைய நிலை",
    completedBadge: "நிறைவடைந்தது",
    auditHistoryLogTitle: "தணிக்கை வரலாற்றுப் பதிவு",
    submittedInformationTitle: "சமர்ப்பிக்கப்பட்ட விவரங்கள்",
    uploadedProofDocsTitle: "பதிவேற்றப்பட்ட சான்று ஆவணங்கள்",
    viewFileBtn: "கோப்பைப் பார்க்கவும்",
    exploreOtherServicesBtn: "பிற இ-சேவைகளைப் பார்க்கவும்",
    needHelpWithApp: "உங்கள் விண்ணப்பத்தில் உதவி தேவையா?",
    contactSupportDeskBtn: "உதவி மையத்தைத் தொடர்பு கொள்ளவும்",
    applicationRejectedTitle: "விண்ணப்பம் நிராகரிக்கப்பட்டது",
    applicationRejectedDesc: "இந்த விண்ணப்பம் அதிகாரியால் நிராகரிக்கப்பட்டுள்ளது. கூடுதல் விவரங்களுக்கு அதிகாரி குறிப்புகளைப் பார்க்கவும்.",
    officerRemarksTitle: "அதிகாரியின் குறிப்புகள்",
    noAuditEventsLogged: "கூடுதல் தணிக்கைப் பதிவுகள் எதுவும் இல்லை.",
    noCustomFieldValues: "சிறப்பு புல தகவல்கள் எதுவும் பதிவு செய்யப்படவில்லை.",
    paymentInformationTitle: "கட்டண விவரங்கள்",
    totalFeeLabel: "மொத்த கட்டணம்",
    txnIdLabel: "பரிவர்த்தனை எண்",
    myPaymentLedgerTitle: "எனது கட்டண பரிவர்த்தனைகள்",
    paymentLedgerSubtitle: "ஆன்லைன் சேவை கட்டணங்களை கண்காணிக்கவும், அதிகாரப்பூர்வ ரசீதுகளை பதிவிறக்கவும் மற்றும் நிலுவையில் உள்ள கட்டணங்களை மீண்டும் செலுத்தவும்.",
    paymentAuditTrailTitle: "கட்டண தணிக்கைப் பதிவு",
    totalRecordsLabel: "மொத்தப் பதிவுகள்",
    loadingLedgerText: "பரிவர்த்தனைப் பதிவுகள் ஏற்றப்படுகின்றன...",
    noPaymentHistoryTitle: "கட்டண வரலாறு எதுவும் பதிவு செய்யப்படவில்லை",
    noPaymentHistoryDesc: "நீங்கள் விண்ணப்பம் சமர்ப்பித்த பிறகு உங்களின் கட்டண ரசீதுகள் இங்கு தோன்றும்.",
    browseServicesBtn: "சேவைகளைப் பார்க்கவும்",
    receiptTxnHeader: "ரசீது / பரிவர்த்தனை எண்",
    appIdHeader: "விண்ணப்ப எண்",
    serviceHeader: "சேவை",
    amountHeader: "தொகை",
    dateHeader: "தேதி",
    statusHeader: "நிலை",
    actionsHeader: "செயல்கள்",
    retryPaymentBtn: "மீண்டும் செலுத்தவும்",
    retrievingStatusRecord: "விண்ணப்ப நிலை பெறப்படுகிறது...",

    // STEP 9 AUTH, DASHBOARD, PROFILE & NOTIFICATION KEYS (TAMIL)
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    loginToAccount: "உங்கள் இ-சேவை கணக்கில் உள்நுழையவும்",
    emailAddressLabel: "மின்னஞ்சல் முகவரி",
    mobileNumberLabel: "மொபைல் எண்",
    passwordLabel: "கடவுச்சொல்",
    confirmPasswordLabel: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    rememberMeLabel: "என்னை நினைவில் வைத்திருக்கவும்",
    forgotPasswordLink: "கடவுச்சொல் மறந்துவிட்டதா?",
    loginBtn: "உள்நுழைக",
    registerBtn: "கணக்கை உருவாக்கவும்",
    dontHaveAccount: "கணக்கு இல்லையா?",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    showPassword: "கடவுச்சொல்லைக் காண்பி",
    hidePassword: "கடவுச்சொல்லை மறை",
    fullNameLabel: "முழுப் பெயர்",
    createAccountTitle: "கணக்கை உருவாக்கவும்",
    forgotPasswordTitle: "கடவுச்சொல் மறந்துவிட்டதா?",
    forgotPasswordDesc: "கடவுச்சொல்லை மீட்டமைக்கும் இணைப்பைப் பெற உங்கள் பதிவுசெய்த மின்னஞ்சல் முகவரியை உள்ளிடவும்.",
    sendResetLinkBtn: "மீட்டமைப்பு இணைப்பை அனுப்பவும்",
    backToLoginLink: "உள்நுழைவுக்குத் திரும்பவும்",
    emailRequiredErr: "மின்னஞ்சல் முகவரி அவசியம்",
    mobileRequiredErr: "மொபைல் எண் அவசியம்",
    passwordRequiredErr: "கடவுச்சொல் அவசியம்",
    invalidEmailOrPasswordErr: "மின்னஞ்சல் அல்லது கடவுச்சொல் தவறாக உள்ளது",
    invalidMobileErr: "சரியான மொபைல் எண்ணை உள்ளிடவும்",
    tryAgainText: "மீண்டும் முயற்சிக்கவும்",
    nameRequiredErr: "பெயர் அவசியம்",
    passwordsDoNotMatchErr: "கடவுச்சொற்கள் பொருந்தவில்லை",
    passwordCriteriaErr: "கடவுச்சொல் தேவையான விதிமுறைகளை பூர்த்தி செய்ய வேண்டும்",
    dashboardTitle: "டாஷ்போர்டு",
    welcomeUserPrefix: "வரவேற்கிறோம்,",
    totalApplicationsCard: "மொத்த விண்ணப்பங்கள்",
    pendingCard: "நிலுவையில்",
    underReviewCard: "மதிப்பாய்வில்",
    processingCard: "செயலாக்கத்தில்",
    approvedCard: "அங்கீகரிக்கப்பட்டது",
    completedCard: "நிறைவடைந்தது",
    rejectedCard: "நிராகரிக்கப்பட்டது",
    recentApplicationsTitle: "சமீபத்திய விண்ணப்பங்கள்",
    viewAllBtn: "அனைத்தையும் பார்க்கவும்",
    quickActionsTitle: "விரைவு செயல்கள்",
    applyServiceAction: "சேவைக்கு விண்ணப்பிக்கவும்",
    trackAppAction: "விண்ணப்ப நிலையைப் பார்க்கவும்",
    viewProfileAction: "சுயவிவரத்தைப் பார்க்கவும்",
    searchApplicationsPlaceholder: "விண்ணப்பங்களைத் தேடவும்...",
    filterLabel: "வடிகட்டி",
    allFilter: "அனைத்தும்",
    noApplicationsFound: "விண்ணப்பங்கள் எதுவும் கிடைக்கவில்லை",
    noApplicationsDesc: "நீங்கள் இன்னும் எந்த விண்ணப்பத்தையும் சமர்ப்பிக்கவில்லை.",
    profileTitle: "சுயவிவரம்",
    personalInfoTitle: "தனிப்பட்ட தகவல்கள்",
    addressLabel: "முகவரி",
    editProfileBtn: "சுயவிவரத்தைத் திருத்தவும்",
    saveChangesBtn: "மாற்றங்களைச் சேமிக்கவும்",
    cancelBtn: "ரத்து செய்",
    accountSettingsTitle: "கணக்கு அமைப்புகள்",
    changePasswordTitle: "கடவுச்சொல்லை மாற்றவும்",
    notificationsTitle: "அறிவிப்புகள்",
    languageTitle: "மொழி",
    securityTitle: "பாதுகாப்பு",
    markAsReadBtn: "படித்ததாகக் குறிக்கவும்",
    markAllAsReadBtn: "அனைத்தையும் படித்ததாகக் குறிக்கவும்",
    noNotificationsText: "அறிவிப்புகள் எதுவும் இல்லை",
    confirmLogoutTitle: "நிச்சயமாக வெளியேற விரும்புகிறீர்களா?",
    yesLogoutBtn: "ஆம், வெளியேறு"
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('eseva_lang') || 'en';
  });

  useEffect(() => {
    document.documentElement.lang = lang;
    document.body.setAttribute('data-lang', lang);
  }, [lang]);

  const toggleLanguage = () => {
    const nextLang = lang === 'en' ? 'ta' : 'en';
    setLang(nextLang);
    localStorage.setItem('eseva_lang', nextLang);
  };

  const setLanguage = (newLang) => {
    if (newLang === 'en' || newLang === 'ta') {
      setLang(newLang);
      localStorage.setItem('eseva_lang', newLang);
    }
  };

  const t = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
