import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  en: {
    // 1. HEADER
    portalName: "E-SEVA PORTAL",
    tagline: "Digital Services Made Easy",
    govTag: "GOVERNMENT OF TAMIL NADU E-SEVA SERVICES",
    home: "Home",
    services: "Services",
    eServices: "Services",
    allServices: "All Services",
    aboutUs: "About Us",
    about: "About Us",
    contactUs: "Contact Us",
    contact: "Contact Us",
    trackAppNav: "Track Application",
    checkStatus: "Track Application",
    more: "More",
    login: "Login",
    registerNav: "Register",
    profileNav: "Profile",
    dashboardNav: "Dashboard",
    myApplicationsNav: "My Applications",
    logoutNav: "Logout",
    
    // 2. COMMON BUTTONS
    applyNow: "Apply Now",
    viewDetails: "View Details",
    learnMore: "Learn More",
    getStarted: "Get Started",
    submitBtn: "Submit",
    continueBtn: "Continue",
    nextBtn: "Next",
    previousBtn: "Previous",
    backBtn: "Back",
    cancelBtn: "Cancel",
    saveBtn: "Save",
    editBtn: "Edit",
    deleteBtn: "Delete",
    searchBtn: "Search",
    filterBtn: "Filter",
    clearBtn: "Clear",
    closeBtn: "Close",
    confirmBtn: "Confirm",
    downloadBtn: "Download",
    uploadBtn: "Upload",
    viewBtn: "View",
    updateBtn: "Update",
    refreshBtn: "Refresh",
    retryBtn: "Retry",

    // 3. SERVICE CATEGORIES
    catAadhaar: "Aadhaar Services",
    catPan: "PAN Services",
    catVoter: "Voter ID Services",
    catCertificate: "Certificate Services",
    catLandPatta: "Land & Patta Services",
    catPassport: "Passport Services",
    catDriving: "Driving Licence Services",
    catVehicle: "Vehicle Services",
    catBusiness: "Business Services",
    catUtility: "Utility Services",
    catOther: "Other Digital Services",

    // 4. AADHAAR SERVICES
    aadhaarEnrollment: "New Aadhaar Enrollment",
    aadhaarNameUpdate: "Aadhaar Name Update",
    aadhaarAddressUpdate: "Aadhaar Address Update",
    aadhaarMobileUpdate: "Aadhaar Mobile Number Update",
    aadhaarEmailUpdate: "Aadhaar Email Update",
    aadhaarDobUpdate: "Aadhaar Date of Birth Update",
    aadhaarGenderUpdate: "Aadhaar Gender Update",
    aadhaarPhotoUpdate: "Aadhaar Photo Update",
    aadhaarBiometricUpdate: "Aadhaar Biometric Update",
    aadhaarDocumentUpdate: "Aadhaar Document Update",
    aadhaarDownload: "Aadhaar Download",
    aadhaarPvc: "Aadhaar PVC Card",
    aadhaarStatusCheck: "Aadhaar Status Check",
    aadhaarCorrection: "Aadhaar Correction Assistance",
    aadhaarPanLink: "Aadhaar-PAN Linking Assistance",

    // 5. PAN SERVICES
    panNew: "New PAN Card",
    panCorrection: "PAN Card Correction",
    panReprint: "PAN Card Reprint",
    panStatusCheck: "PAN Status Check",
    panAadhaarLink: "PAN-Aadhaar Linking",
    panDownload: "PAN Download",

    // 6. COMMON FORM LABELS
    fullNameLabel: "Full Name",
    firstNameLabel: "First Name",
    lastNameLabel: "Last Name",
    dobLabel: "Date of Birth",
    genderLabel: "Gender",
    mobileLabel: "Mobile Number",
    emailLabel: "Email Address",
    fatherNameLabel: "Father's Name",
    motherNameLabel: "Mother's Name",
    addressLabel: "Address",
    doorNoLabel: "House / Door Number",
    streetLabel: "Street",
    areaLabel: "Area",
    cityTownLabel: "City / Town",
    districtLabel: "District",
    stateLabel: "State",
    pincodeLabel: "Pincode",

    // 7. DOCUMENTS
    documentsHeader: "Documents",
    uploadDocumentsHeader: "Upload Documents",
    requiredDocumentsHeader: "Required Documents",
    identityProof: "Identity Proof",
    addressProof: "Address Proof",
    dobProof: "Date of Birth Proof",
    documentNameLabel: "Document Name",
    chooseFileBtn: "Choose File",
    noFileSelected: "No File Selected",
    uploadSuccessful: "Upload Successful",
    uploadFailed: "Upload Failed",

    // 8. APPLICATION
    applicationLabel: "Application",
    applicationFormHeader: "Application Form",
    applicationDetailsHeader: "Application Details",
    applicationIdLabel: "Application ID",
    applicationStatusLabel: "Application Status",
    applicationDateLabel: "Application Date",
    submittedOnLabel: "Submitted On",
    reviewApplicationHeader: "Review Application",
    submitApplicationBtn: "Submit Application",
    trackApplicationHeader: "Track Application",

    // 9. APPLICATION STATUS
    statusDraft: "Draft",
    statusSubmitted: "Submitted",
    statusUnderReview: "Under Review",
    statusProcessing: "Processing",
    statusApproved: "Approved",
    statusCompleted: "Completed",
    statusRejected: "Rejected",

    // 10. PAYMENT
    paymentHeader: "Payment",
    paymentDetailsHeader: "Payment Details",
    serviceFeeLabel: "Service Fee",
    totalAmountLabel: "Total Amount",
    paymentStatusLabel: "Payment Status",
    payNowBtn: "Pay Now",
    paymentSuccessfulMsg: "Payment Successful",
    paymentFailedMsg: "Payment Failed",
    transactionIdLabel: "Transaction ID",
    paymentReceiptHeader: "Payment Receipt",

    payStatusPending: "Pending",
    payStatusProcessing: "Processing",
    payStatusPaid: "Paid",
    payStatusFailed: "Failed",
    payStatusCancelled: "Cancelled",
    payStatusRefunded: "Refunded",

    // 11. USER DASHBOARD
    dashDashboard: "Dashboard",
    dashMyApplications: "My Applications",
    dashRecentApplications: "Recent Applications",
    dashTotalApplications: "Total Applications",
    dashPendingApplications: "Pending Applications",
    dashCompletedApplications: "Completed Applications",
    dashProfileSettings: "Profile Settings",
    dashAccountSettings: "Account Settings",
    dashNotifications: "Notifications",

    // 12. LOGIN / REGISTER
    authWelcomeBack: "Welcome Back",
    authLoginSub: "Login to your account",
    authEmail: "Email",
    authPassword: "Password",
    authConfirmPassword: "Confirm Password",
    authForgotPass: "Forgot Password?",
    authDontHaveAccount: "Don't have an account?",
    authCreateAccount: "Create Account",
    authAlreadyHaveAccount: "Already have an account?",

    // 13. COMMON MESSAGES
    msgPleaseWait: "Please wait",
    msgLoading: "Loading...",
    msgNoDataFound: "No data found",
    msgNoAppsFound: "No applications found",
    msgSomethingWentWrong: "Something went wrong",
    msgPleaseTryAgain: "Please try again",
    msgAreYouSure: "Are you sure?",
    msgChangesSavedSuccess: "Changes saved successfully",
    msgAppSubmittedSuccess: "Application submitted successfully",

    // Hero & Extra Helpers
    heroTitle: "One Portal for All Digital Government Services",
    heroSubtitle: "Apply for Community, Income, Aadhaar, Patta, PAN, Voter ID and Utility services online with instant verification and SMS tracking.",
    searchPlaceholder: "Search services (Aadhaar, PAN, Patta, Income Certificate)...",
    activeServicesCount: "100+ Active Services",
    digitalProcessing: "100% Paperless & Secure",
    fastDelivery: "2-3 Days Fast Processing",
    allCategories: "All Service Categories",
    welcomeUser: "Welcome,",
    userDashboardTitle: "User Dashboard & Application Cockpit",
    userDashboardDesc: "Manage your applications, view progress, and access 100+ digital services.",
    quickActions: "Quick Actions",
    applyNewService: "Apply for New Service",
    trackAppStatus: "Track Application Status",
    viewPaymentLedger: "View Payment History",
    appId: "Application ID",
    serviceName: "Service Name",
    appliedDate: "Applied Date",
    status: "Status",
    action: "Action",
    trackTitle: "Track Application Status",
    trackSubtitle: "Enter your Application ID to view current progress and download issued certificates.",
    enterAppId: "Enter Application ID (e.g., APP-2026-8492)",
    trackNow: "Track Now",
    statusTimeline: "Application Processing Timeline",
    dateSubmitted: "Date Submitted",
    lastUpdated: "Last Updated",
    trackingHelp: "Need help tracking your application? Contact our 24/7 helpline at 1800-425-1337.",
    rememberMe: "Remember me",
    forgotPasswordLink: "Forgot Password?",
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: "Already have an account?",
    registerNow: "Register Now",
    loginBtn: "Sign In",
    registerBtn: "Create Account",
    resetPasswordBtn: "Send Reset Link",
    personalInfo: "Personal Information",
    saveChanges: "Save Changes",
    changePassword: "Change Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    notificationPrefs: "Notification Preferences",
    emailNotifications: "Email Notifications",
    smsNotifications: "SMS Notifications",
    transactionId: "Transaction ID",
    paymentDate: "Payment Date",
    amountPaid: "Amount Paid",
    downloadReceiptBtn: "Download PDF Receipt",
    popularServices: "Popular E-Seva Digital Services",
    viewAllServices: "View All Directory →",
    howItWorks: "How E-Seva Portal Works",
    footerDesc: "Official Digital E-Seva Services Gateway empowering citizens with transparent, fast, and accessible digital governance.",
    quickLinks: "Quick Links",
    helpDesk: "Helpline & Support",
    tollFree: "Toll Free Helpline: 1800-425-1337",
    workingHours: "Mon - Sat: 9:00 AM - 6:00 PM",
    copyright: "© 2026 E-Seva Portal. Government of Tamil Nadu Digital Governance Project."
  },
  ta: {
    // 1. HEADER
    portalName: "இ-சேவை போர்ட்டல்",
    tagline: "மின்னணு சேவைகள் எளிதாக",
    govTag: "தமிழ்நாடு அரசு மின்னணு இ-சேவை மையம்",
    home: "முகப்பு",
    services: "சேவைகள்",
    eServices: "சேவைகள்",
    allServices: "அனைத்து சேவைகள்",
    aboutUs: "எங்களைப் பற்றி",
    about: "எங்களைப் பற்றி",
    contactUs: "தொடர்புகொள்ள",
    contact: "தொடர்புகொள்ள",
    trackAppNav: "விண்ணப்பத்தை கண்காணிக்க",
    checkStatus: "விண்ணப்பத்தை கண்காணிக்க",
    more: "மேலும்",
    login: "உள்நுழைய",
    registerNav: "பதிவு செய்ய",
    profileNav: "சுயவிவரம்",
    dashboardNav: "முகப்புப்பலகை",
    myApplicationsNav: "எனது விண்ணப்பங்கள்",
    logoutNav: "வெளியேற",
    
    // 2. COMMON BUTTONS
    applyNow: "இப்போது விண்ணப்பிக்கவும்",
    viewDetails: "விவரங்களைப் பார்க்கவும்",
    learnMore: "மேலும் அறியவும்",
    getStarted: "தொடங்கவும்",
    submitBtn: "சமர்ப்பிக்கவும்",
    continueBtn: "தொடரவும்",
    nextBtn: "அடுத்து",
    previousBtn: "முந்தையது",
    backBtn: "பின்செல்",
    cancelBtn: "ரத்து செய்யவும்",
    saveBtn: "சேமிக்கவும்",
    editBtn: "திருத்தவும்",
    deleteBtn: "நீக்கவும்",
    searchBtn: "தேடவும்",
    filterBtn: "வடிகட்டி",
    clearBtn: "அழிக்கவும்",
    closeBtn: "மூடவும்",
    confirmBtn: "உறுதிப்படுத்தவும்",
    downloadBtn: "பதிவிறக்கவும்",
    uploadBtn: "பதிவேற்றவும்",
    viewBtn: "பார்க்கவும்",
    updateBtn: "புதுப்பிக்கவும்",
    refreshBtn: "புதுப்பிக்கவும்",
    retryBtn: "மீண்டும் முயற்சிக்கவும்",

    // 3. SERVICE CATEGORIES
    catAadhaar: "ஆதார் சேவைகள்",
    catPan: "PAN அட்டை சேவைகள்",
    catVoter: "வாக்காளர் அட்டை சேவைகள்",
    catCertificate: "சான்றிதழ் சேவைகள்",
    catLandPatta: "நிலம் மற்றும் பட்டா சேவைகள்",
    catPassport: "பாஸ்போர்ட் சேவைகள்",
    catDriving: "ஓட்டுநர் உரிமம் சேவைகள்",
    catVehicle: "வாகன சேவைகள்",
    catBusiness: "வணிக சேவைகள்",
    catUtility: "பயன்பாட்டு சேவைகள்",
    catOther: "பிற டிஜிட்டல் சேவைகள்",

    // 4. AADHAAR SERVICES
    aadhaarEnrollment: "புதிய ஆதார் பதிவு",
    aadhaarNameUpdate: "ஆதார் பெயர் புதுப்பிப்பு",
    aadhaarAddressUpdate: "ஆதார் முகவரி புதுப்பிப்பு",
    aadhaarMobileUpdate: "ஆதார் மொபைல் எண் புதுப்பிப்பு",
    aadhaarEmailUpdate: "ஆதார் மின்னஞ்சல் புதுப்பிப்பு",
    aadhaarDobUpdate: "ஆதார் பிறந்த தேதி புதுப்பிப்பு",
    aadhaarGenderUpdate: "ஆதார் பாலினம் புதுப்பிப்பு",
    aadhaarPhotoUpdate: "ஆதார் புகைப்பட புதுப்பிப்பு",
    aadhaarBiometricUpdate: "ஆதார் பயோமெட்ரிக் புதுப்பிப்பு",
    aadhaarDocumentUpdate: "ஆதார் ஆவண புதுப்பிப்பு",
    aadhaarDownload: "ஆதார் பதிவிறக்கம்",
    aadhaarPvc: "ஆதார் PVC அட்டை",
    aadhaarStatusCheck: "ஆதார் நிலையைச் சரிபார்க்கவும்",
    aadhaarCorrection: "ஆதார் திருத்த உதவி",
    aadhaarPanLink: "ஆதார்-PAN இணைப்பு உதவி",

    // 5. PAN SERVICES
    panNew: "புதிய PAN அட்டை",
    panCorrection: "PAN அட்டை திருத்தம்",
    panReprint: "PAN அட்டை மறுபதிப்பு",
    panStatusCheck: "PAN நிலையைச் சரிபார்க்கவும்",
    panAadhaarLink: "PAN-Aadhaar இணைப்பு",
    panDownload: "PAN பதிவிறக்கம்",

    // 6. COMMON FORM LABELS
    fullNameLabel: "முழுப் பெயர்",
    firstNameLabel: "முதல் பெயர்",
    lastNameLabel: "கடைசி பெயர்",
    dobLabel: "பிறந்த தேதி",
    genderLabel: "பாலினம்",
    mobileLabel: "மொபைல் எண்",
    emailLabel: "மின்னஞ்சல் முகவரி",
    fatherNameLabel: "தந்தையின் பெயர்",
    motherNameLabel: "தாயின் பெயர்",
    addressLabel: "முகவரி",
    doorNoLabel: "வீட்டு / கதவு எண்",
    streetLabel: "தெரு",
    areaLabel: "பகுதி",
    cityTownLabel: "நகரம் / ஊர்",
    districtLabel: "மாவட்டம்",
    stateLabel: "மாநிலம்",
    pincodeLabel: "அஞ்சல் குறியீடு",

    // 7. DOCUMENTS
    documentsHeader: "ஆவணங்கள்",
    uploadDocumentsHeader: "ஆவணங்களைப் பதிவேற்றவும்",
    requiredDocumentsHeader: "தேவையான ஆவணங்கள்",
    identityProof: "அடையாளச் சான்று",
    addressProof: "முகவரிச் சான்று",
    dobProof: "பிறந்த தேதி சான்று",
    documentNameLabel: "ஆவணத்தின் பெயர்",
    chooseFileBtn: "கோப்பைத் தேர்ந்தெடுக்கவும்",
    noFileSelected: "எந்தக் கோப்பும் தேர்ந்தெடுக்கப்படவில்லை",
    uploadSuccessful: "பதிவேற்றம் வெற்றிகரமாக முடிந்தது",
    uploadFailed: "பதிவேற்றம் தோல்வியடைந்தது",

    // 8. APPLICATION
    applicationLabel: "விண்ணப்பம்",
    applicationFormHeader: "விண்ணப்பப் படிவம்",
    applicationDetailsHeader: "விண்ணப்ப விவரங்கள்",
    applicationIdLabel: "விண்ணப்ப எண்",
    applicationStatusLabel: "விண்ணப்ப நிலை",
    applicationDateLabel: "விண்ணப்ப தேதி",
    submittedOnLabel: "சமர்ப்பிக்கப்பட்ட தேதி",
    reviewApplicationHeader: "விண்ணப்பத்தை மதிப்பாய்வு செய்யவும்",
    submitApplicationBtn: "விண்ணப்பத்தை சமர்ப்பிக்கவும்",
    trackApplicationHeader: "விண்ணப்பத்தை கண்காணிக்கவும்",

    // 9. APPLICATION STATUS
    statusDraft: "வரைவு",
    statusSubmitted: "சமர்ப்பிக்கப்பட்டது",
    statusUnderReview: "பரிசீலனையில் உள்ளது",
    statusProcessing: "செயலாக்கத்தில் உள்ளது",
    statusApproved: "அங்கீகரிக்கப்பட்டது",
    statusCompleted: "நிறைவு பெற்றது",
    statusRejected: "நிராகரிக்கப்பட்டது",

    // 10. PAYMENT
    paymentHeader: "கட்டணம்",
    paymentDetailsHeader: "கட்டண விவரங்கள்",
    serviceFeeLabel: "சேவை கட்டணம்",
    totalAmountLabel: "மொத்த தொகை",
    paymentStatusLabel: "கட்டண நிலை",
    payNowBtn: "இப்போது செலுத்தவும்",
    paymentSuccessfulMsg: "கட்டணம் வெற்றிகரமாக செலுத்தப்பட்டது",
    paymentFailedMsg: "கட்டணம் தோல்வியடைந்தது",
    transactionIdLabel: "பரிவர்த்தனை எண்",
    paymentReceiptHeader: "கட்டண ரசீது",

    payStatusPending: "நிலுவையில் உள்ளது",
    payStatusProcessing: "செயலாக்கத்தில் உள்ளது",
    payStatusPaid: "செலுத்தப்பட்டது",
    payStatusFailed: "தோல்வியடைந்தது",
    payStatusCancelled: "ரத்து செய்யப்பட்டது",
    payStatusRefunded: "பணம் திருப்பி வழங்கப்பட்டது",

    // 11. USER DASHBOARD
    dashDashboard: "முகப்புப்பலகை",
    dashMyApplications: "எனது விண்ணப்பங்கள்",
    dashRecentApplications: "சமீபத்திய விண்ணப்பங்கள்",
    dashTotalApplications: "மொத்த விண்ணப்பங்கள்",
    dashPendingApplications: "நிலுவையிலுள்ள விண்ணப்பங்கள்",
    dashCompletedApplications: "நிறைவு பெற்ற விண்ணப்பங்கள்",
    dashProfileSettings: "சுயவிவர அமைப்புகள்",
    dashAccountSettings: "கணக்கு அமைப்புகள்",
    dashNotifications: "அறிவிப்புகள்",

    // 12. LOGIN / REGISTER
    authWelcomeBack: "மீண்டும் வரவேற்கிறோம்",
    authLoginSub: "உங்கள் கணக்கில் உள்நுழையவும்",
    authEmail: "மின்னஞ்சல்",
    authPassword: "கடவுச்சொல்",
    authConfirmPassword: "கடவுச்சொல்லை உறுதிப்படுத்தவும்",
    authForgotPass: "கடவுச்சொல்லை மறந்துவிட்டீர்களா?",
    authDontHaveAccount: "கணக்கு இல்லையா?",
    authCreateAccount: "கணக்கை உருவாக்கவும்",
    authAlreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",

    // 13. COMMON MESSAGES
    msgPleaseWait: "தயவுசெய்து காத்திருக்கவும்",
    msgLoading: "ஏற்றப்படுகிறது...",
    msgNoDataFound: "தரவு எதுவும் கிடைக்கவில்லை",
    msgNoAppsFound: "விண்ணப்பங்கள் எதுவும் கிடைக்கவில்லை",
    msgSomethingWentWrong: "ஏதோ தவறு ஏற்பட்டுள்ளது",
    msgPleaseTryAgain: "தயவுசெய்து மீண்டும் முயற்சிக்கவும்",
    msgAreYouSure: "நீங்கள் உறுதியாக உள்ளீர்களா?",
    msgChangesSavedSuccess: "மாற்றங்கள் வெற்றிகரமாக சேமிக்கப்பட்டன",
    msgAppSubmittedSuccess: "விண்ணப்பம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது",

    // Hero & Extra Helpers
    heroTitle: "அனைத்து அரசு சேவைகளுக்கும் ஒரே இணையதளம்",
    heroSubtitle: "வருமானம், சாதி, ஆதார், பட்டா, பான், வாக்காளர் அட்டை மற்றும் பிற மின் சேவைகளுக்கு ஆன்லைனில் விண்ணப்பித்து உடனடி நிலை அறியலாம்.",
    searchPlaceholder: "சேவைகளைத் தேடவும் (ஆதார், பான், பட்டா, வருமானச் சான்றிதழ்)...",
    activeServicesCount: "100+ நேரலை சேவைகள்",
    digitalProcessing: "100% பாதுகாப்பான மின்னணு முறை",
    fastDelivery: "2-3 நாட்களில் விரைவு சேவை",
    allCategories: "அனைத்து சேவைப் பிரிவுகள்",
    welcomeUser: "வரவேற்கிறோம்,",
    userDashboardTitle: "பயனர் டாஷ்போர்டு & விண்ணப்ப மையம்",
    userDashboardDesc: "உங்கள் விண்ணப்பங்களைக் கண்காணிக்கலாம் மற்றும் 100+ சேவைகளுக்கு விண்ணப்பிக்கலாம்.",
    quickActions: "விரைவுச் செயல்பாடுகள்",
    applyNewService: "புதிய சேவைக்கு விண்ணப்பிக்க",
    trackAppStatus: "விண்ணப்ப நிலையை அறிய",
    viewPaymentLedger: "கட்டண வரலாற்றைப் பார்க்க",
    appId: "விண்ணப்ப எண்",
    serviceName: "சேவையின் பெயர்",
    appliedDate: "விண்ணப்பித்த தேதி",
    status: "தற்போதைய நிலை",
    action: "செயல்பாடு",
    trackTitle: "விண்ணப்ப நிலையை அறிதல்",
    trackSubtitle: "தற்போதைய நிலையைப் பார்க்க மற்றும் சான்றிதழ் பதிவிறக்கம் செய்ய விண்ணப்ப எண்ணை உள்ளிடவும்.",
    enterAppId: "விண்ணப்ப எண்ணை உள்ளிடவும் (எ.கா: APP-2026-8492)",
    trackNow: "நிலை அறிய",
    statusTimeline: "விண்ணப்ப பரிசீலனை நிலைகள்",
    dateSubmitted: "சமர்ப்பிக்கப்பட்ட தேதி",
    lastUpdated: "கடைசியாக புதுப்பிக்கப்பட்டது",
    trackingHelp: "உதவி தேவையா? கட்டணமில்லா உதவி எண்ணை அழைக்கவும்: 1800-425-1337.",
    rememberMe: "என்னை நினைவில் கொள்க",
    forgotPasswordLink: "கடவுச்சொல் மறந்துவிட்டதா?",
    dontHaveAccount: "கணக்கு இல்லையா?",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    registerNow: "இப்போதே பதிவு செய்ய",
    loginBtn: "உள்நுழைக",
    registerBtn: "கணக்கை உருவாக்கு",
    resetPasswordBtn: "மீட்டமைப்பு இணைப்பு அனுப்புக",
    personalInfo: "தனிப்பட்ட விவரங்கள்",
    saveChanges: "மாற்றங்களைச் சேமி",
    changePassword: "கடவுச்சொல்லை மாற்றுக",
    currentPassword: "தற்போதைய கடவுச்சொல்",
    newPassword: "புதிய கடவுச்சொல்",
    notificationPrefs: "அறிவிப்பு விருப்பங்கள்",
    emailNotifications: "மின்னஞ்சல் அறிவிப்புகள்",
    smsNotifications: "குறுஞ்செய்தி (SMS) அறிவிப்புகள்",
    transactionId: "பரிவர்த்தனை எண்",
    paymentDate: "செலுத்திய தேதி",
    amountPaid: "செலுத்தப்பட்ட தொகை",
    downloadReceiptBtn: "PDF ரசீது பதிவிறக்கம்",
    popularServices: "முக்கியமான இ-சேவைகள்",
    viewAllServices: "அனைத்து சேவைகளையும் பார்க்க →",
    howItWorks: "இ-சேவை போர்ட்டல் எவ்வாறு செயல்படுகிறது?",
    footerDesc: "பொதுமக்களுக்கு வேகமான, வெளிப்படையான டிஜிட்டல் அரசு சேவைகளை வழங்கும் அதிகாரப்பூர்வ இ-சேவை போர்ட்டல்.",
    quickLinks: "முக்கிய இணைப்புகள்",
    helpDesk: "உதவி மையம் & ஆதரவு",
    tollFree: "கட்டணமில்லா உதவி எண்: 1800-425-1337",
    workingHours: "திங்கள் - சனி: காலை 9:00 - மாலை 6:00",
    copyright: "© 2026 இ-சேவை போர்ட்டல். தமிழ்நாடு அரசு டிஜிட்டல் ஆளுகைத் திட்டம்."
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('eseva_lang') || 'en';
  });

  const toggleLanguage = () => {
    const nextLang = lang === 'en' ? 'ta' : 'en';
    setLang(nextLang);
    localStorage.setItem('eseva_lang', nextLang);
  };

  const setLanguage = (newLang) => {
    if (newLang === 'en' || newLang === 'ta') {
      setLang(newLang);
      localStorage.setItem('eseva_lang', newLang);
    }
  };

  const t = translations[lang] || translations.en;

  return (
    <LanguageContext.Provider value={{ lang, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
